use P1_JoseRuiz;
GO


-- CONSULTA 1
SELECT APELLIDOS_NOMBRE FROM PLANTILLA
WHERE APELLIDOS_NOMBRE LIKE 'H%';


-- CONSULTA 2
SELECT APELLIDOS_NOMBRE FROM PLANTILLA
WHERE TURNO IN ('T', 'M') AND FUNCION IN ('Enfermero', 'Enfermera');

-- CONSULTA 3
SELECT APELLIDOS_NOMBRE, SALARIO FROM PLANTILLA
WHERE FUNCION = 'Enfermera' AND SALARIO BETWEEN 20000 AND 25000;

-- CONSULTA 4
SELECT LEFT(NOMBRE, 3) AS ABR, HOSPITAL_COD, NOMBRE FROM HOSPITAL
ORDER BY ABR;

-- CONSULTA 5
SELECT APELLIDOS_NOMBRE, SALARIO/12 AS 'SALARIO MENSUAL' FROM PLANTILLA
WHERE FUNCION IN('Enfermera', 'Enfermero');

-- CONSULTA 6
SELECT AVG(SALARIO) AS SALARIO_MEDIO FROM PLANTILLA
WHERE FUNCION IN('Enfermero');

-- CONSULTA 7
SELECT MAX(SALARIO) AS 'SALARIO_MAXIMO', MIN(SALARIO) AS 'SALARIO_MINIMO', MAX(SALARIO)-MIN(SALARIO) AS 'DIFERENCIA' FROM PLANTILLA

-- CONSULTA 8
SELECT FUNCION AS PUESTO, AVG(SALARIO) AS SALARIO_MEDIO FROM PLANTILLA
GROUP BY FUNCION;

-- CONSULTA 9
SELECT FUNCION AS PUESTO, COUNT(*) AS NUMERO FROM PLANTILLA
GROUP BY FUNCION;

-- CONSULTA 10
SELECT H.NOMBRE AS HOSPITAL, S.NOMBRE AS SALA, P.FUNCION, P.APELLIDOS_NOMBRE FROM PLANTILLA P
JOIN HOSPITAL H ON P.HOSPITAL_COD = H.HOSPITAL_COD
JOIN SALA S ON P.HOSPITAL_COD = S.HOSPITAL_COD AND P.SALA_COD = S.SALA_COD
ORDER BY H.NOMBRE, P.FUNCION, P.APELLIDOS_NOMBRE;

-- CONSULTA 11
UPDATE PLANTILLA 
SET FUNCION = 'ENFERMERO'
WHERE UPPER(FUNCION) = 'ENFERMO'
SELECT * FROM PLANTILLA;

-- CONSULTA 12
UPDATE HOSPITAL 
SET NUM_CAMA = ROUND(NUM_CAMA * 1.10, 2);
SELECT * FROM HOSPITAL;

