//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public string CIF { get; set; }
        public string NOMBRE { get; set; }
        public string E_MAIL { get; set; }
        public string TELEFONO { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
